import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { NextUIProviders } from "@/components/providers/nextUi-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <ClerkProvider>
        <body>
          <NextUIProviders>
            {children}
          </NextUIProviders>
        </body>
      </ClerkProvider>
    </html>
  );
}
