import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { NextUIProviders } from "@/components/providers/nextUi-provider";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
        <body>
          <NextUIProviders>
            <main>{children}</main>
            <Toaster />
          </NextUIProviders>
        </body>
    </html>
  );
}

{/* <ClerkProvider appearance={{
  baseTheme: dark
}}> */}